### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by cloneniu** [liuruoze/mini-AlphaStar#12]
It is very exciting to see the implementation of Alphastar after 2 years since release of the paper. I am trying to run miniAlphaStar. But after a few tries I am stuck at an error. Could you give me some help?

Steps I take:  
1. install the environment with "conda create -n th_1_5 python=3.7 pytorch=1.5 -c pytorch", "conda activate th_1_5" and "pip install -r requirements.txt". conda version 4.8.2.
2. download StarCraft from "http://blzdistsc2-a.akamaihd.net/Linux/SC2.4.6.0.67926.zip" in page "https://github.com/Blizzard/s2client-proto" and unzip to ~/
3. download all maps from "https://github.com/Blizzard/s2client-proto" and move them to ~/StarCraftII/Maps/
4. download replays with command "python download_replays.py --key=mykey --secret=mysecrete --version="4.6.0" --download_dir=./download/download-4-6 --extract --replays_dir=./replay/replay-4-6 --filter_version="delete"
5. make a soft link "data/Replays/filtered_replays_1/" to "replay/replay-4-6"
6. change line 71 of mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py from "flags.DEFINE_string("replay_version", "3.16.1", "the replays released by blizzard are all 3.16.1 version")" to "flags.DEFINE_string("replay_version", "4.6.0", "the replays released by blizzard are all 4.1.2 version")"
7. change "flags.DEFINE_string("no_server_replay_path", "D:/work/gitproject/mini-AlphaStar/data/Replays/small_simple64_replays/", "path of replay data")" to "flags.DEFINE_string("no_server_replay_path", "/home/user/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-6/", "path of replay data")"

then "python run.py"

but I got following error:

```Game has started.
  0%|                                     | 10/60474 [00:29<19:04:31,  1.14s/it]Traceback (most recent call last):
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 493, in test
    feature, label = getFeatureAndLabel_numpy(obs, func_call)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 135, in getFeatureAndLabel_numpy
    s = Agent.get_state_and_action_from_pickle_numpy(obs)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/agent.py", line 95, in get_state_and_action_from_pickle_numpy
    batch_entities_tensor = Agent.preprocess_state_entity_numpy(obs)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/agent.py", line 355, in preprocess_state_entity_numpy
    entities_array = ArchModel.preprocess_entity_numpy(e_list)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/arch_model.py", line 88, in preprocess_entity_numpy
    return EntityEncoder.preprocess_numpy(e_list)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/entity_encoder.py", line 111, in preprocess_numpy
    return cls.preprocess_in_numpy(entity_list)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/entity_encoder.py", line 524, in preprocess_in_numpy
    order_queue_length_encoding = L.np_one_hot(np.array([order_queue_length]), cls.max_order_queue_length).reshape(1, -1)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/lib/utils.py", line 280, in np_one_hot
    res = np.eye(nb_classes)[np.array(targets).reshape(-1)]
IndexError: index 9 is out of bounds for axis 0 with size 9```

Firstly I tried Starcraft 4.1.2, but there is a pysc2 websocket timeout issue. Then I tried 4.6. The websocket timeout issue is gone but this index out of bound error arises. 

My OS is ubuntu 20.04.3.

**Comment by liuruoze** [comment]
Yes, this problem is quite easy. That's because the index 9 can't be placed into a hot-hot matrix that has a max of 9 (the Maximus index should be 8 instead of  9).

You can add a line "order_queue_length = min(order_queue_length, 8)" after "order_queue_length = entity.order_length". 

The master version of this project also solves the problem.

Sorry for those too many bugs. The project is still on development, so codes may be unstable and some bugs will occur.

**Comment by cloneniu** [comment]
I am reading the code now and know there are around 16000 lines of code in this fantastic repo. This number is reasonable for one person to handle. I'm working on Alphastar for a long time and very enthusiastic for it though far from implementing it. May I join you? It will be my honor.  

I also sent you email to liuruoze@163.com.

**Comment by liuruoze** [comment]
I am very excited to see someone who wants to join the development of SC2. But before you join me, you should show your determination on this work. StarCraft2 is very complicated, and AlphaStar (and mini-AlphaStar) needs much knowledge to implement. The way you choose is to show me a plan for your work.

Nowadays mini-AlphaStar's basic structure is constructed. The next job is to improve on its specific unideal parts. You should choose and make think about what the part you want to work and improve on? You can do this as the following.

1: which part of mini-AlphaStar is weak?
2: what is the reason for that weakness?
3: what is your plan to do an improvement path over this part?
4: how much time would you spend on doing that?

When the above questions have a clear answer, you can discuss them with me. We can negotiate a pathway to do it.

**Comment by cloneniu** [comment]
Sure. I totally agree with you. Do you mind offer a cpu (or gpu) docker as test environment to run miniAlphastar on? A Dockerfile is enough, a tar docker is better. It's really painful to debug the environment and dependent issue. This will be of great help toward goals mentioned above.

**Comment by cloneniu** [comment]
I encounter a libEGL issue, details below. I believe it is caused by my nvidia driver. Is there a way to turn off gpu and use only my cpu for testing?

```Command Line: '"/home/ats/StarCraftII/Versions/Base67926/SC2_x64" -listen 127.0.0.1 -port 24522 -dataDir /home/ats/StarCraftII/ -tempDir /tmp/sc-to9s71n5/ -dataVersion 7DE59231CBF06F1ECE9A25A27964D4AE -eglpath libEGL.so.1'
Starting up...
Startup Phase 1 complete
Startup Phase 2 complete
Attempting to initialize EGL from file libEGL.so.1 ...
Successfully loaded EGL library!
libEGL warning: MESA-LOADER: failed to open nouveau: /usr/lib/dri/nouveau_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open nouveau: /usr/lib/dri/nouveau_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

Failed to create and initialize a valid EGL display! Devices tried: 3

CreateInitializedEGLDisplay Failed.
Failed to initialize GL framework
Creating stub renderer...
Listening on: 127.0.0.1:24522```

**Comment by cloneniu** [comment]
I failed to find a detailed and complete document for pysc or sc2client-api. I know [s2client-api doc](https://github.com/Blizzard/s2client-api/tree/master/docs) and [pysc2 doc](https://github.com/deepmind/pysc2/tree/master/docs). But funcions like ```run_configs``` or ```feature_from_game_info``` are not explained. Did you read through resource code in order to understand functions you need? I guess there are some ealier work to refer. Could you give me some hints?

**Comment by cloneniu** [comment]
Which os(mac, win or linux) and StarCraft version is the one you successfully run miniAlphastar with. I use Ubuntu 20.04 and StarCraft Linux 4.6. As you can see the logs below, I am not sure if the ```WARNING:absl:Not found tag! 4342939649``` is fatal, but I guess ```KeyError: 'effect_id'``` is caused by version conflict. The log is for test() in "alphastarmini\core\sl\transform_replay_data.py"

```replay_path: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-6/fdf2bc0b9318a0b3ae7795076ce73946b3082eedd5f31ab1f13ea4f7d66da023.SC2Replay
infos len 2
need_observe_id 1
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Starting replay 'TempStartReplay.SC2Replay'
Game has started.
WARNING:absl:Not found tag! 4342939649
WARNING:absl:Not found tag! 4342939649
Traceback (most recent call last):
  File "/home/ats/anaconda3/envs/th_1_5/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 271, in _get_index
    return self._index_names[dim][index]
KeyError: 'effect_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ats/anaconda3/envs/th_1_5/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 139, in __getattr__
    return self[name]
  File "/home/ats/anaconda3/envs/th_1_5/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 151, in __getitem__
    indices = self._indices(indices)
  File "/home/ats/anaconda3/envs/th_1_5/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 265, in _indices
    return self._get_index(0, indices)
  File "/home/ats/anaconda3/envs/th_1_5/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 273, in _get_index
    raise KeyError("Name '%s' is invalid for axis %s." % (index, dim))
KeyError: "Name 'effect_id' is invalid for axis 0."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 572, in test
    print('end save!')
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 138, in getFeatureAndLabel_numpy
    s = Agent.get_state_and_action_from_pickle_numpy(obs)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/agent.py", line 83, in get_state_and_action_from_pickle_numpy
    scalar_list = Agent.preprocess_state_scalar_numpy(obs, build_order=None)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/agent.py", line 253, in preprocess_state_scalar_numpy
    return ArchModel.preprocess_scalar_numpy(obs, build_order=build_order)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/arch_model.py", line 80, in preprocess_scalar_numpy
    return ScalarEncoder.preprocess_numpy(obs, build_order=build_order)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/scalar_encoder.py", line 323, in preprocess_numpy
    e = effect.effect_id
  File "/home/ats/anaconda3/envs/th_1_5/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 141, in __getattr__
    raise AttributeError("Bad attribute name: %s" % name)
AttributeError: Bad attribute name: effect_id
Traceback (most recent call last):
  File "/home/ats/anaconda3/envs/th_1_5/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 271, in _get_index
    return self._index_names[dim][index]
KeyError: 'effect_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ats/anaconda3/envs/th_1_5/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 139, in __getattr__
    return self[name]
  File "/home/ats/anaconda3/envs/th_1_5/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 151, in __getitem__
    indices = self._indices(indices)
  File "/home/ats/anaconda3/envs/th_1_5/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 265, in _indices
    return self._get_index(0, indices)
  File "/home/ats/anaconda3/envs/th_1_5/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 273, in _get_index
    raise KeyError("Name '%s' is invalid for axis %s." % (index, dim))
KeyError: "Name 'effect_id' is invalid for axis 0."
```

**Comment by liuruoze** [comment]
1. The "effect_id" problem is so strange, could you give me some more information? Actually, it is a property in sc2-API and pysc2. Commonly it shouldn't arise a problem. Try to change the version of SC2 may the problem be alleviated?  (this can be set in the create function of SC2Env, you can see the "VERSION" in rl_vs_computer_wo_replay.py to see how we achieve it)

2. Yes, actually, the doc for pysc2 is very limited. I read directly from its source code. When a specific problem or something which I don't know appears, I search in the source code of pysc2.  Also, when the code in pysc2 didn't give the answer, I will directly go to see sc2-API proto file.

3. To disable GPU, you should easily set the line in run.py 'USED_DEVICES = "0"' to 'USED_DEVICES = "-1"'。 This change will affect all the programs. You need not change other things.

4. I am not very familiar with Docker, should some future time would this be considered. Also, some help is welcome.

**Comment by cloneniu** [comment]
This is ```effected_id``` log.  
ubuntu 20.04, gtx750ti, driver version 470.74, Starcraft 4.6.0
```
(torch_1_7) root@e5d9f377f0f7:/home/ats/Project/mini-AlphaStar# python run.py
pygame 2.1.0 (SDL 2.0.16, Python 3.7.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
run init
run_config <pysc2.run_configs.platforms.Linux object at 0x7f0e16ff72d0>
REPLAY_PATH: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-10/
length of replay_files: 100448
screen_resolution <class 'pysc2.lib.point.Point'> 64,64
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/root/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 15493 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-rb0zlcmi/ -dataVersion B89B5D6FA7CBF6452E721311BFBC6CB2 -headlessNoRender'
Starting up...
Startup Phase 1 complete
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:15493
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:34670 accepted
ReadyHandler: 127.0.0.1:34670 ready
  0%|                                                                                                                                 | 0/100448 [00:00<?, ?it/s]replay_path: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-10/ffff0bb56c715099d18d197e35a571e45687334f619f1b53b8e7037c922b0b06.SC2Replay
infos len 2
need_observe_id 0
no need_observe_id found! continue
replay_path: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-10/fffc22e3c6fda50c96e70e37ba36ebc23442a0c573423a423341b08be2fe7fc5.SC2Replay
infos len 2
need_observe_id 0
no need_observe_id found! continue
replay_path: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-10/fffc1daa51cc9a5b27e56da43bf1243c2f17b81463368cde7536df3676ca9d95.SC2Replay
infos len 2
need_observe_id 1
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Starting replay 'TempStartReplay.SC2Replay'
Game has started.
Using default stable ids, none found at: /root/StarCraftII/stableid.json
Successfully loaded stable ids: GameData\stableid.json
[player_id: 1
result: Victory
, player_id: 2
result: Defeat
]
begin save!
end save!
  0%|                                                                                                                    | 3/100448 [02:19<1293:23:18, 46.36s/it]replay_path: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-10/fff956421e7bf453cbb83d124963a5430dee4d2bb2660911190f997618d35d13.SC2Replay
infos len 2
need_observe_id 0
no need_observe_id found! continue
replay_path: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-10/fff902bed18a8ad068833d80c3c649bc7bd0888b868561f3f7cde57271f0460e.SC2Replay
infos len 2
need_observe_id 0
no need_observe_id found! continue
replay_path: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-10/fff8fe6fe8198a6409b700ab965f3d331286d1f5fb8b3ad5b769639bd6432a2e.SC2Replay
infos len 2
need_observe_id 0
no need_observe_id found! continue
replay_path: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-10/fff8456666397cda597746320ed0f3ea88d942babc5c38340e3e7742b781dea8.SC2Replay
infos len 2
need_observe_id 0
no need_observe_id found! continue
replay_path: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-10/fff6b02f9e3e5c63df107bfadfb1284a47e8cea8ff6169373ebee54128fbfbf0.SC2Replay
infos len 2
need_observe_id 0
no need_observe_id found! continue
replay_path: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-10/fff45b838e6c5d0fa47a7b358c84449f6d9d0614c4aaa86ed1e4f9bf50e22300.SC2Replay
infos len 2
need_observe_id 0
no need_observe_id found! continue
replay_path: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-10/ffeec26dd7eeebce2c5a653cbf44b94fd63eab30f626ee4d4610d8b922eda09e.SC2Replay
infos len 2
need_observe_id 0
no need_observe_id found! continue
  0%|                                                                                                                    | 10/100448 [02:19<905:27:25, 32.45s/it]replay_path: /home/ats/Project/mini-AlphaStar/scripts/download_replay/third/replay/replay-4-10/ffeddbad22bf3961a4188c4640567c04d9bc43d91febacfcdf5a9c1478966ee6.SC2Replay
infos len 2
need_observe_id 1
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Starting replay 'TempStartReplay.SC2Replay'
Game has started.
  0%|                                                                                                                    | 10/100448 [02:30<905:27:25, 32.45s/it]WARNING:absl:Not found tag! 8614576129
Traceback (most recent call last):
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 271, in _get_index
    return self._index_names[dim][index]
KeyError: 'effect_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 139, in __getattr__
    return self[name]
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 151, in __getitem__
    indices = self._indices(indices)
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 265, in _indices
    return self._get_index(0, indices)
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 273, in _get_index
    raise KeyError("Name '%s' is invalid for axis %s." % (index, dim))
KeyError: "Name 'effect_id' is invalid for axis 0."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 507, in test
    feature, label = getFeatureAndLabel_numpy(obs, func_call)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 138, in getFeatureAndLabel_numpy
    s = Agent.get_state_and_action_from_pickle_numpy(obs)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/agent.py", line 83, in get_state_and_action_from_pickle_numpy
    scalar_list = Agent.preprocess_state_scalar_numpy(obs, build_order=None)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/agent.py", line 253, in preprocess_state_scalar_numpy
    return ArchModel.preprocess_scalar_numpy(obs, build_order=build_order)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/arch_model.py", line 81, in preprocess_scalar_numpy
    return ScalarEncoder.preprocess_numpy(obs, build_order=build_order)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/scalar_encoder.py", line 323, in preprocess_numpy
    e = effect.effect_id
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 141, in __getattr__
    raise AttributeError("Bad attribute name: %s" % name)
AttributeError: Bad attribute name: effect_id
Traceback (most recent call last):
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 271, in _get_index
    return self._index_names[dim][index]
KeyError: 'effect_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 139, in __getattr__
    return self[name]
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 151, in __getitem__
    indices = self._indices(indices)
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 265, in _indices
    return self._get_index(0, indices)
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 273, in _get_index
    raise KeyError("Name '%s' is invalid for axis %s." % (index, dim))
KeyError: "Name 'effect_id' is invalid for axis 0."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 507, in test
    feature, label = getFeatureAndLabel_numpy(obs, func_call)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 138, in getFeatureAndLabel_numpy
    s = Agent.get_state_and_action_from_pickle_numpy(obs)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/agent.py", line 83, in get_state_and_action_from_pickle_numpy
    scalar_list = Agent.preprocess_state_scalar_numpy(obs, build_order=None)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/agent.py", line 253, in preprocess_state_scalar_numpy
    return ArchModel.preprocess_scalar_numpy(obs, build_order=build_order)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/arch_model.py", line 81, in preprocess_scalar_numpy
    return ScalarEncoder.preprocess_numpy(obs, build_order=build_order)
  File "/home/ats/Project/mini-AlphaStar/alphastarmini/core/arch/scalar_encoder.py", line 323, in preprocess_numpy
    e = effect.effect_id
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 141, in __getattr__
    raise AttributeError("Bad attribute name: %s" % name)
AttributeError: Bad attribute name: effect_id
Traceback (most recent call last):
  File "/root/anaconda3/envs/torch_1_7/lib/python3.7/site-packages/pysc2/lib/named_array.py", line 271, in _get_index
    return self._index_names[dim][index]
KeyError: 'effect_id'

[player_id: 1
result: Victory
, player_id: 2
result: Defeat
]
begin save!
CloseHandler: 127.0.0.1:34670 disconnected
Killed
```

**Comment by cloneniu** [comment]
I am wondering why the first Traceback is so shallow. It doesn't show any information about the calling function.

**Comment by liuruoze** [comment]
Please see this line "Version: B75689 (SC2.4.10)"

Actually, you start an SC2 version which is SC2 4.10.

I recommend using an older replay version to try, e.g., 4.6.

Moreover, please try using the latest code of the main branch. It has fixed a lot of problems.

**Comment by cloneniu** [comment]
Thank you for the update. I ran the code successfully in a gpu docker. But the program eat up all the memory when dealing with the first sample in replay folder. What is the minimum memory requirement?  I have 32G.
By the way, do you consider replacing ```print``` with ```logging```? Traceback the code with logging file rather than with terminal history is a lot easier.  
Did you filter the "mmr" for the replay? I think supervise training with high "mmr" is what we need. There are totally 60473 replay file I download for the Version: B67926 (SC2.4.6). And the "mmr" filtering is also mentioned in the alphastar paper.

**Comment by liuruoze** [comment]
1. If you have about 30-40G memory, you should use the pickle format to save and process the replay files. In a server with 450G memory, I processed at most 15 replays saving in the tensor format at once. The memory usage actually has room for optimization. When in the future I have time, I will collect some time to do it. 

2. Using logging to replace print is a sound suggestion. We can try it in a later version as a new feature.

3. MMR filter is not used now. Actually, we filter some specific replays as we want, e.g., Protoss vs. Protoss on AbyssalReef. By this setting, we gathered a total of 608 replays. The MMR filter can be used in the future.

**Comment by cloneniu** [comment]
I created a docker for testing this repo. Please check [mini-alphastar docker](https://hub.docker.com/r/hanxiwu/mini-alphastar).   
I updated the image(around 28G). You can find Dockerfile in the "Overview" tag.  
Docker can easily be deployed on cpu/gpu server or on k8s cluster.  
If you find any problem please let me know.

**Comment by cloneniu** [comment]
I pulled your latest 1375637c commit but transform replay failed. 8c18233cf6e works fine.

**Comment by cloneniu** [comment]
Oh. I notice it is because of the DATA_NUM.

**Comment by cloneniu** [comment]
NUM_WORKERS should be 0 for docker environment due to limited shared memory.

**Comment by cloneniu** [comment]
Why use ```model.sl_forward``` and ```model.forward``` again in function ```get_sl_loss_for_tensor``` in file ```alphastarmini/core/sl/sl_loss_multi_gpu.py```?

**Comment by cloneniu** [comment]
```winloss_baseline``` is not only for ```action_type``` right? [link](https://github.com/liuruoze/mini-AlphaStar/blob/85e02049215b1b29f01c7ae0f06ca7cebb9b2488/alphastarmini/core/arch/baseline.py#L29)

**Comment by cloneniu** [comment]
Hi, I find there are two kind of forward one is ```forward``` and the other is ```sl_forward```. I know the ```sl``` version is for supervised learning. But what exactly is the difference?

**Comment by cloneniu** [comment]
Using ```typing``` for variables, at least for function parameters and class variables, will make code easier to read.

**Comment by liuruoze** [comment]
> Hi, I find there are two kind of forward one is `forward` and the other is `sl_forward`. I know the `sl` version is for supervised learning. But what exactly is the difference?

The difference is that when we want to predict a sequence, assuming the ground truth is "ABCCDB", the forward will first output a predict A' for A, and then use **A'** to predict the next value, like B'. On the contrary, the sl_forward will first output a predict A' for A, and then use  **A** to predict the next value, like B'. Using sl_forward, we can inject the ground truth in the predicted sequence, thus improving the learning effectiveness. Note considers the **sl_forward** using the ground truth information, it can only be used in the learning process. In the inference process, we can only use the **forward** function.

**Comment by cloneniu** [comment]
Hi, I find this very interesting [torch typing](https://github.com/patrick-kidger/torchtyping)?

**Comment by liuruoze** [comment]
Hi, 

if there are no more things to discuss, I will close the issue now. 

For new things (or new problems) to discuss, we can open a new issue to discuss. 

Thank you!
