### ISSUE TITLE
Starcraft 2 version problem

### ISSUE THREAD

**Issue by khcf123** [liuruoze/mini-AlphaStar#17]
Hi, I am having latest starcraft 2 version which is 5.0.8 on windows 10, when I try to run " python run.py" with codes below: 

# # 5. we use SL model and replays to do reinforcement learning
    from alphastarmini.core.rl import rl_train_with_replay
    rl_train_with_replay.test(on_server=P.on_server, replay_path=P.replay_path)

Result with error below:

ActorLoop.run() Exception cause return, Detials of the Exception: Unknown game version: 3.16.1. Known versions: ['latest'].
Traceback (most recent call last):
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\rl\actor_plus_z.py", line 130, in run
    run_config = run_configs.get(version=self.replay_version)  # the replays released by blizzard are all 3.16.1 version
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\run_configs\__init__.py", line 40, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\run_configs\platforms.py", line 121, in __init__
    version=version, cwd="Support64")
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\run_configs\platforms.py", line 63, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\run_configs\lib.py", line 112, in __init__
    self.version = self._get_version(version)
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\run_configs\lib.py", line 220, in _get_version
    versions = self.get_versions(containing=game_version)
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\run_configs\platforms.py", line 109, in get_versions
    containing, sorted(ret.keys())))
ValueError: Unknown game version: 3.16.1. Known versions: ['latest'].

run over

Which I know it needs SC2 3.16.1 version to work, but I cannot get older version of Starcraft 2. Please advice me on this. Thanks!!

**Comment by khcf123** [comment]
I knew it already, you need to open the replay in order to get older version of Starcraft 2.

**Comment by liuruoze** [comment]
> I knew it already, you need to open the replay in order to get older version of Starcraft 2.

Yes, in windows, this is the way to get the older version of SC2. Actually, all versions of SC2 all reside in the same folder, the "versions" directory in the SC2 installation directory.

**Comment by khcf123** [comment]
Hi, now I have another issue as shown below:

pygame 2.1.2 (SDL 2.0.18, Python 3.7.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
run init
cudnn available
cudnn version 7604
start_time before training: 2022-01-02 10:08:24
map name: AbyssalReef
player.name: MainPlayer
opponent.name: Historical
player.race: Race.protoss
opponent.race: Race.protoss
ActorLoop.run() Exception cause return, Detials of the Exception: Unknown game version: 4.10.0. Known versions: ['3.16.1', 'latest'].
Traceback (most recent call last):
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\rl\actor_plus_z.py", line 132, in run
    with self.create_env(self.player, self.opponent) as env:
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\rl\actor_plus_z.py", line 451, in create_env
    random_seed=random_seed)
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\env\sc2_env.py", line 264, in __init__
    self._run_config = run_configs.get(version=version)
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\run_configs\__init__.py", line 40, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\run_configs\platforms.py", line 121, in __init__
    version=version, cwd="Support64")
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\run_configs\platforms.py", line 63, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\run_configs\lib.py", line 112, in __init__
    self.version = self._get_version(version)
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\run_configs\lib.py", line 220, in _get_version
    versions = self.get_versions(containing=game_version)
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\pysc2\run_configs\platforms.py", line 109, in get_versions
    containing, sorted(ret.keys())))
ValueError: Unknown game version: 4.10.0. Known versions: ['3.16.1', 'latest'].

run over

**Comment by liuruoze** [comment]
It seems that you are using "actor_plus_z" to do RL training. 

We suggest you first do supervise learning. After you get an initial model, you can do RL training based on the supervised learning model. If not, the RL training will be much difficult. The agent can not even get any positive signal if it explores by random.

**Comment by khcf123** [comment]
I tried to do supervise learning by running these codes in run.py:

 # # 1. we transform the replays to pickle
    from alphastarmini.core.sl import transform_replay_data
    transform_replay_data.test(on_server=False)

# we can use pickle to do supervised learning
    from alphastarmini.core.sl import sl_train_by_pickle
    sl_train_by_pickle.test(on_server=P.on_server)

And my outcome is error shown as below:

replay_path: C:/Program Files (x86)/StarCraft II/Replays/fff1607182d598eea7d26a9efba5bbc003a271fd032d1495b1b02fff93058ea8.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/fff3cc2ee9bc8a7c0e19329799bb9aacc843cee0b2d0390c061c19661bfabdb6.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/fff55f71950f68d75bc2f6ab8b62fddca4a5ee3077ff06acc167b52ca4bfa6dc.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/fff5693bfa9c3cd278e3280ed93c5bae6a31c9b19d2a3d4bd4a20438acb89533.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/fff5cd144641fdbca1f7676192789a14af046fcad1cbdc784a4de082cd80bd7b.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/fff7fd96485150057985175bc0aa6780bd6e83a57b442d1049a7fce98f6d3a35.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/fffcdcef0b6f34f2ede51a01be2cdde29b2cdb6dbc411536c81a145d536dc2c1.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/fffeb3a896ef4cd46cab661b935966952d9307673dcdc96cb971bf87da3cacb3.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/fffeb9b9437fde426b5e51a700bd339e0eedb127a2106ff9920b65c2bccfd4f4.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/ffff487609735303a99e2d156b9d28163d0b371fe4e69cc31940ce66d2f6bb9e.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/ffffac3c77fe8697d6be7164068299499a517244bb741c92b5b10199130e9948.SC2Replay
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64396/64396 [00:02<00:00, 25971.50it/s]
end
replay_length_list: []
noop_length_list: []
Traceback (most recent call last):
  File "run.py", line 71, in <module>
    sl_train_by_pickle.test(on_server=P.on_server)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\sl_train_by_pickle.py", line 265, in test
    max_file_size=FILE_SIZE, shuffle=True)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\dataset_pickle.py", line 104, in get_trainable_data
    replay_files = os.listdir(replay_data_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: './data/replay_data/'

Please help me on this, thanks

**Comment by liuruoze** [comment]
Are you using the v_1.06 release? If not, please switch to that release. In that version, we recommend you to use the train_by_tensors to train the replays. You need first transform the replays to tensors. After you have done that, please ask your question here. We will give you guides for later actions.

**Comment by khcf123** [comment]
Ok, i am using v_1.06 release version. I try transform replays to tensors. In run.py, I run codes below:

 # # 1. we transform the replays to pickle
    from alphastarmini.core.sl import transform_replay_data
    transform_replay_data.test(on_server=P.on_server)

# transform pickles data to tensor data for supervised learning
    from alphastarmini.core.sl import load_pickle
    load_pickle.test(on_server=False)

In transform_replay_data.py, I do this changes:

flags.DEFINE_string("no_server_replay_path", "C:/Program Files (x86)/StarCraft II/Replays/", "path of replay data")

And the outcome is shown below with error:

replay_path: C:/Program Files (x86)/StarCraft II/Replays/fff5cd144641fdbca1f7676192789a14af046fcad1cbdc784a4de082cd80bd7b.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/fff7fd96485150057985175bc0aa6780bd6e83a57b442d1049a7fce98f6d3a35.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/fffcdcef0b6f34f2ede51a01be2cdde29b2cdb6dbc411536c81a145d536dc2c1.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/fffeb3a896ef4cd46cab661b935966952d9307673dcdc96cb971bf87da3cacb3.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/fffeb9b9437fde426b5e51a700bd339e0eedb127a2106ff9920b65c2bccfd4f4.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/ffff487609735303a99e2d156b9d28163d0b371fe4e69cc31940ce66d2f6bb9e.SC2Replay
replay_path: C:/Program Files (x86)/StarCraft II/Replays/ffffac3c77fe8697d6be7164068299499a517244bb741c92b5b10199130e9948.SC2Replay
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64396/64396 [00:02<00:00, 26174.10it/s]
end
replay_length_list: []
noop_length_list: []
Traceback (most recent call last):
  File "run.py", line 84, in <module>
    load_pickle.test(on_server=False)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\load_pickle.py", line 112, in test
    from_pickle_to_tensor(FLAGS.replay_data_path, FLAGS.save_tensor_path, 15, 20)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\load_pickle.py", line 47, in from_pickle_to_tensor
    replay_files = os.listdir(pickle_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: './data/replay_data/'

Please help me, thanks

**Comment by khcf123** [comment]
I knew it, you must copy maps folder from "C:\Program Files (x86)\StarCraft II\Battle.net\Cache" to "C:\ProgramData\Blizzard Entertainment\Battle.net\Cache"

**Comment by khcf123** [comment]
In run.py, I run codes below:

# # 2. we use tensor to do supervised learning
    from alphastarmini.core.sl import sl_train_by_tensor
    sl_train_by_tensor.test(on_server=P.on_server)

And the outcome is shown below with error:

Traceback (most recent call last):
  File "run.py", line 60, in <module>
    sl_train_by_tensor.test(on_server=P.on_server)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\sl_train_by_tensor.py", line 548, in test
    main_worker(DEVICE)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\sl_train_by_tensor.py", line 226, in main_worker
    val_set, batch_iter, epoch, val_loader)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\sl_train_by_tensor.py", line 261, in train
    train=True)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\sl_loss_multi_gpu.py", line 269, in get_sl_loss_for_tensor
    multi_gpu_supvised_learning=True)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\arch\arch_model.py", line 148, in forward
    map_skip, embedded_spatial = self.spatial_encoder(state.map_state, entity_embeddings)
  File "C:\Users\alexa\anaconda3\envs\torch_1_5\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\arch\spatial_encoder.py", line 139, in forward
    scatter_entity = self.scatter(scatter_map, entity_embeddings)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\arch\spatial_encoder.py", line 112, in scatter
    scatter_mid = reduced_entity_embeddings.gather(1, scatter_index.long())
RuntimeError: CUDA out of memory. Tried to allocate 18.00 MiB (GPU 0; 2.00 GiB total capacity; 1.28 GiB already allocated; 0 bytes free; 1.34 GiB reserved in total by PyTorch)

Please help me, thanks

**Comment by liuruoze** [comment]
Hi, @khcf123  this is due to your GPU memory is not enough for training. 

Sorry for replying so late. I am focusing on coding for the last week (there are some hard obstacles for me to handle). 

You can change the "batch_size" and "sequence_length" in the "MiniStar_Arch_Hyper_Parameters" in "lib/hyper_parameters.py" to reduce the demands for GPU memory usage. 

I will close the issue now. If you find your problems not solved, you can reopen this issue. 

Good luck!
