### ISSUE TITLE
回放文件Replays

### ISSUE THREAD

**Issue by ZHQ-air** [liuruoze/mini-AlphaStar#7]
您好，关于“data/Replays/filtered_replays_1”中的回放文件是怎么得到的呀？ 我尝试的操作是：利用sc2client-proto/samples/replay-api/download_replays.py下载与我的StarCraftII（4.9.3）对应版本的回放文件，但是运行download_replays.py文件时提示“Failed to get oauth access token.”，其中我的运行命令是 python download_replays.py --key=我的battle.net邮箱账号 --secret=我的battle.net账号密码 --version=4.9.3 --replays_dir=/home/zhq/Doctor/RL_Project/s2client-proto/samples/replay-api/replays --extract。
       请问下，这种情况是怎么回事呀？

**Comment by liuruoze** [comment]
事实上，我也没有试过这种方法（我用的是官网下3.16.1的replay pack）。

这个问题你已经解决了么？

**Comment by ZHQ-air** [comment]
还没解决，我也在官网下载了3.16.1-pack_1(5G大小) 和 3.16.1pack_2(50G大小)两个replay pack。你是直接把3.16.1-pack_1里面的replay pack 放到 data/Replays/filtered_replays_1/ 文件夹里面了么？

**Comment by liuruoze** [comment]
对

**Comment by ZHQ-air** [comment]
您好，我也在官网下载了3.16.1-pack_1，然后将replay pack放到StarCraftII文件中，位置为 StarCraftII中Replays的位置 /home/zhq/StarCraftII/Replays/；同时，我也将这个replay pack放到了mini-AlphaStar/data/文件夹内
         我在transform_replay_data.py中给REPLAY_PATH变量赋值为：REPLAY_PATH = "/home/zhq/Doctor/RL_Project/mini-AlphaStar/data/Replays/"
         但是运行transform_replay_data.py后提示错误：
```
Traceback (most recent call last):
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/protocol.py", line 151, in send
    res = self.send_req(req)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/protocol.py", line 130, in send_req
    self.write(request)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/protocol.py", line 126, in write
    self._write(request)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/protocol.py", line 196, in _write
    self._sock.send(request_str)
  File "/home/zhq/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/protocol.py", line 68, in catch_websocket_connection_errors
    raise ConnectionError("Connection already closed. SC2 probably crashed. "
pysc2.lib.protocol.ConnectionError: Connection already closed. SC2 probably crashed. Check the error log.
```

**Comment by liuruoze** [comment]
这个信息量太少了点，你需要先看看在文件循环中，你处理到了每个文件了么？把replay名字打印出来看下。

replay_pack是要先解压的

另外，在SC2传进去的进程中，版本要匹配，例如，应该用3.16.1的版本的SC2，这个在

#line 303
run_config = run_configs.get(version=FLAGS.replay_version)

这里修改

**Comment by ZHQ-air** [comment]
好的，太感谢您啦！我再试试。

**Comment by ZHQ-air** [comment]
您好，我的SC2版本之前是4.9.3的，现在换成3.16.1的了。但是运行代码出了如下的问题，麻烦您再看下呀,我提取了终端中输出的部分信息（没显示的错误信息基本和这个是同类型的）

```
(base) zhq@Ubuntu20:~/Doctor/RL_Project/mini-AlphaStar$ python run.py 
arch init
sl init
rl init
lt init
core init
transformer init
third init
lib init
alphastarmini init
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
run init
replay_version-----------------------------------------------: 3.16.1
REPLAY_PATH----------------------------------------------: /home/zhq/Doctor/RL_Project/mini-AlphaStar/data/Replays/
length of replay_files-----------------------------------------------: 64396
Version: B55958 (SC2.3.16)
Build: Jul 31 2017 13:19:41
Command Line: '"/home/zhq/StarCraftII/Versions/Base55958/SC2_x64" -listen 127.0.0.1 -port 23944 -dataDir /home/zhq/StarCraftII/ -tempDir /tmp/sc-rgjv64_b/ -dataVersion 5BD7C31B44525DAB46E64C4602A81DC2 -eglpath libEGL.so'
Starting up...
Startup Phase 1 complete
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:23944 (23944)
Startup Phase 3 complete. Ready for commands.
  0%|                                                                                              | 0/64396 [00:00<?, ?it/s]replay_path: /home/zhq/Doctor/RL_Project/mini-AlphaStar/data/Replays/ffffac3c77fe8697d6be7164068299499a517244bb741c92b5b10199130e9948.SC2Replay
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Launching next game.
Next launch phase started: 2
Error during launch: 7
Traceback (most recent call last):
  File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 376, in test
    controller.start_replay(start_replay)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/remote_controller.py", line 99, in _valid_status
    return func(self, *args, **kwargs)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/remote_controller.py", line 74, in _check_error
    return check_error(func(*args, **kwargs), error_enum)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/remote_controller.py", line 65, in check_error
    raise RequestError("%s.%s: '%s'" % (enum_name, error_name, details), res)
pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseStartReplay.Error.LaunchError: 'The launch of this game makes reference to mod or map dependencies which are no longer available.'
replay_path: /home/zhq/Doctor/RL_Project/mini-AlphaStar/data/Replays/ffff487609735303a99e2d156b9d28163d0b371fe4e69cc31940ce66d2f6bb9e.SC2Replay
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Launching next game.
Next launch phase started: 2
Error during launch: 7
Traceback (most recent call last):
  File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 376, in test
    controller.start_replay(start_replay)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/remote_controller.py", line 99, in _valid_status
    return func(self, *args, **kwargs)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/remote_controller.py", line 74, in _check_error
    return check_error(func(*args, **kwargs), error_enum)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/remote_controller.py", line 65, in check_error
    raise RequestError("%s.%s: '%s'" % (enum_name, error_name, details), res)
pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseStartReplay.Error.LaunchError: 'The launch of this game makes reference to mod or map dependencies which are no longer available.'
replay_path: /home/zhq/Doctor/RL_Project/mini-AlphaStar/data/Replays/fffeb9b9437fde426b5e51a700bd339e0eedb127a2106ff9920b65c2bccfd4f4.SC2Replay
Failed to open the map archive: /home/zhq/StarCraftII/Battle.net\Cache/fd/88/fd8898dbe586fa967760980debcad0ce20610fb447cd0697c109d4ebf7d1d5cf.s2ma
Could not find map name for file: /tmp/sc-rgjv64_b/StarCraft II/TempReplayInfo.SC2Replay
Traceback (most recent call last):
  File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 362, in test
    replay_info = controller.replay_info(replay_data)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/remote_controller.py", line 74, in _check_error
    return check_error(func(*args, **kwargs), error_enum)
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/pysc2/lib/remote_controller.py", line 65, in check_error
    raise RequestError("%s.%s: '%s'" % (enum_name, error_name, details), res)
pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseReplayInfo.Error.ParsingError: 'Possible corruption - Failed to open the map archive: /home/zhq/StarCraftII/Battle.net\Cache/fd/88/fd8898dbe586fa967760980debcad0ce20610fb447cd0697c109d4ebf7d1d5cf.s2ma'
replay_path: /home/zhq/Doctor/RL_Project/mini-AlphaStar/data/Replays/fffeb3a896ef4cd46cab661b935966952d9307673dcdc96cb971bf87da3cacb3.SC2Replay
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
```

**Comment by liuruoze** [comment]
The launch of this game makes reference to mod or map dependencies which are no longer available.

/home/zhq/StarCraftII/Battle.net\Cache/fd/88/fd8898dbe586fa967760980debcad0ce20610fb447cd0697c109d4ebf7d1d5cf.s2ma

你看下，是这个图找不到

你是在windows上还是在linux上玩的？

如果是windows，首先直接打开这个replay，然后游戏会自动下图。

如果是linux，操作还是一样的，先在window上打开这个图，然后把”/StarCraftII/Battle.net\Cache/fd/88“这个目录下的文件复制到linux上的同级别的目录下

**或者简单的办法，一气呵成解决（推荐）：**
(Or use a simple way, to do it)

打开下面的url，按照步骤做第一和第二个动作
(Open the URL below and to the first and second actions in this URL)
https://colab.research.google.com/drive/1TzO2Wi9KLjfBZeOqjGgjlxmwU5IX4wIV#scrollTo=XoZu1wZWLrfP

如果无法打开的话，直接执行以下两行命令（在linux下）
(if you can't open the URL, direct type the below two commands)
!wget http://blzdistsc2-a.akamaihd.net/Linux/SC2.4.1.2.60604_2018_05_16.zip
!unzip -P iagreetotheeula SC2.4.1.2.60604_2018_05_16.zip -d ~ && rm -rf SC2.4.1.2.60604_2018_05_16.zip

这个操作同时会把很多图下载到cache里，之后你只要把它复制到提示找不到图的地方即可。
(This operation will download many maps to the cache, and then you only need to copy it to the place where the map is not found.)

**Comment by ZHQ-air** [comment]
我是在ubuntu上操作的。我将SC2.4.1.2.60604_2018_05_16.zip解压后的文件放入cache里，没有提示找不到文件的错误，但还提示如下的错误，不知道如下信息是提示的错误么? 是不是我把提示信息中 ValueError: 151 is not a valid Protoss 所对应的文件删掉就可以了啊！  感谢！

```
(base) zhq@Ubuntu20:~/Doctor/RL_Project/mini-AlphaStar$ python run.py 
arch init
sl init
rl init
lt init
core init
transformer init
third init
lib init
alphastarmini init
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
run init
replay_version-----------------------------------------------: 3.16.1
REPLAY_PATH----------------------------------------------: /home/zhq/Doctor/RL_Project/mini-AlphaStar/data/Replays/
length of replay_files-----------------------------------------------: 64396
Version: B55958 (SC2.3.16)
Build: Jul 31 2017 13:19:41
Command Line: '"/home/zhq/StarCraftII/Versions/Base55958/SC2_x64" -listen 127.0.0.1 -port 15548 -dataDir /home/zhq/StarCraftII/ -tempDir /tmp/sc-pjkjv0jw/ -dataVersion 5BD7C31B44525DAB46E64C4602A81DC2 -eglpath libEGL.so'
Starting up...
Startup Phase 1 complete
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:15548 (15548)
Startup Phase 3 complete. Ready for commands.
  0%|                                                                                                       | 0/64396 [00:00<?, ?it/s]replay_path: /home/zhq/Doctor/RL_Project/mini-AlphaStar/data/Replays/ffffac3c77fe8697d6be7164068299499a517244bb741c92b5b10199130e9948.SC2Replay
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Starting replay 'TempStartReplay.SC2Replay'
Game has started.
ValueError: 151 is not a valid Protoss

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 437, in test
    func_call = getFuncCall(o, feat, prev_obs)
  File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/transform_replay_data.py", line 276, in getFuncCall
    unit_type_name = Unit.Protoss(unit_type_id)
  File "/home/zhq/anaconda3/lib/python3.8/enum.py", line 309, in __call__
    return cls.__new__(cls, value)
  File "/home/zhq/anaconda3/lib/python3.8/enum.py", line 600, in __new__
    raise exc
  File "/home/zhq/anaconda3/lib/python3.8/enum.py", line 584, in __new__
    result = cls._missing_(value)
  File "/home/zhq/anaconda3/lib/python3.8/enum.py", line 613, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 151 is not a valid Protoss
ValueError: 104 is not a valid Protoss

During handling of the above exception, another exception occurred:


```

**Comment by liuruoze** [comment]
ValueError: 151 is not a valid Protoss

ValueError: 104 is not a valid Protoss

你这个replay不是神族打神族的，所以在
transform_replay_data.py", line 276, in getFuncCall
    unit_type_name = Unit.Protoss(unit_type_id)

这里报了错，把Protoss改成在replay中的种族

或者把replay本身做下过滤，仅仅保留神族vs神族的

**Comment by ZHQ-air** [comment]
我的replay文件是在s2client-proto给的如下链接中下载的，我是把3.16.1 - Pack 1解压后的文件放入data/Replays文件夹中的，并且将相应文件也放入StarCraftII/Replays文件夹中的。您所说的对replay过滤是怎么操作的呀？是否需要将3.16.1 - Pack 2中的文件也放入相应的Replays文件夹中呢？
```
Replay Packs
3.16.1 - Pack 1
3.16.1 - Pack 2
```

**Comment by liuruoze** [comment]
Replay Packs
3.16.1 - Pack 1
3.16.1 - Pack 2

这两个replay pack都是包括全部的replays，所以每个种族对抗的都有

在   #368行       
print(" Replay info ".center(60, "-")) if debug else None
print(replay_info) if debug else None
print("-" * 60) if debug else None
controller.start_replay(start_replay)

你把replay_info打印出来看看，把debug改成1

可以看到这个replay是哪个种族对哪个种族的

如果要过滤的话，就不要执行controller.start_replay(start_replay)这句话及之后的话
单独起一个文件，每个文件读replay_info，根据种族对抗信息，然后把需要的replay放到另一个文件夹下
之后用那个新的文件夹即可

我们在代码中没有提供过滤的代码，主要是过滤的工作是我一个师弟做的，我直接拿他过滤好的文件压缩包操作的

过滤的代码也不难，直接按照上面的逻辑改一改就可以了

后续我会考虑把这部分代码加进来，不过最近暂时是没空的

**Comment by ZHQ-air** [comment]
明白了，太感谢啦，我试下！

**Comment by ZHQ-air** [comment]
太感谢了！已经成功对原始Replays进行了过滤，并成功运行transform_replay_data.py产生了5个.pickle文件

**Comment by ZHQ-air** [comment]
还有个问题，就是接下来我注释掉transform_replay_data.py，反注释sl_train_by_pickle.py，然后运行代码。出现了如下错误：
```
(base) zhq@Ubuntu20:~/Doctor/RL_Project/mini-AlphaStar$ python run.py 
arch init
sl init
rl init
lt init
core init
transformer init
third init
lib init
alphastarmini init
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
run init
length of replay_files: 5
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 27.47it/s]
training_size: 4
val_size: 1
torch.cuda.device_count(): 1
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    sl_train_by_pickle.test(on_server=P.on_server)
  File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/sl_train_by_pickle.py", line 224, in test
    train_for_val(replays, None, agent)  # select the best hyper-parameters
  File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/sl_train_by_pickle.py", line 132, in train_for_val
    traj = next(iter(train_loader)) # 通过iter()函数获取这些可迭代对象的迭代器。然后我们可以对获取到的迭代器不断使??next()函数来获取下??条数据。iter()函数实际上就是调??了可迭代对象的
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/dataset_pickle.py", line 110, in __getitem__
    replay = self._get_random_trajectory(index)
  File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/dataset_pickle.py", line 105, in _get_random_trajectory
    the_item = next(iter(traj_loader))
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhq/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/dataset_pickle.py", line 73, in __getitem__
    feature, label = obs2feature(obs, self.agent)
  File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/dataset_pickle.py", line 31, in obs2feature
    feature = Feature.state2feature(s)
  File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/feature.py", line 60, in state2feature
    feature_3 = map_data.reshape(batch_size, AHP.map_channels * AHP.minimap_size * AHP.minimap_size)
RuntimeError: shape '[1, 139264]' is invalid for input of size 73728
```
